#!/usr/bin/env python3
"""
Cross-platform replacement for setup_loaf.sh

Usage:
    python setup_loaf.py

Creates:
 - <NAME>/loaf.json
 - <NAME>/main.py   (Streamlit-compatible module)
 - dql_agent_<NAME>.py (if dql_agent.py exists in repo root)

Notes:
 - Works on Windows, macOS, Linux.
 - Does not call sed/awk; edits training script via Python text replace/regex.
"""
from pathlib import Path
import json
import re
import sys
import os
import stat

ATTACKS = [
    "CRUST_CRUSHER",
    "LEECH_LOAF",
    "SANDWICH_TRAP",
    "OVEN_SPRING",
    "SECOND_RISE",
    "INSTANT_YEAST",
    "GLUTEN_SURGE",
]

def prompt_loaf_name():
    import re
    while True:
        name = input("Enter a name for your loaf (letters, numbers, -, _ only): ").strip()
        if not name:
            print("Name cannot be empty.")
            continue
        if re.match(r'^[A-Za-z0-9_-]+$', name):
            return name
        print("Invalid characters. Use only letters, numbers, hyphen, or underscore.")

def prompt_stats():
    print("You have 6 extra stat points to distribute across Flour, Salt, Sugar.")
    while True:
        try:
            flour = int(input("Extra Flour (0-6): ").strip())
            salt = int(input("Extra Salt  (0-6): ").strip())
            sugar = int(input("Extra Sugar (0-6): ").strip())
        except ValueError:
            print("Please enter integers only.")
            continue
        if any(x < 0 or x > 6 for x in (flour, salt, sugar)):
            print("Each value must be between 0 and 6.")
            continue
        if not 0 <= flour + salt + sugar <= 6:
            print(f"The three numbers must sum between 6. Currently they sum to {flour + salt + sugar}. Try again.")
            continue
        return flour, salt, sugar

def prompt_attacks():
    print("\nSelect 1 to 3 attacks by number (separated by spaces).")
    for i, a in enumerate(ATTACKS, start=1):
        print(f"  {i}) {a}")
    while True:
        raw = input("Enter choices (e.g. 1 4 7): ").strip()
        if not raw:
            print("Please enter your choices.")
            continue
        parts = re.split(r'[\s,]+', raw)
        try:
            nums = [int(p) for p in parts if p]
        except ValueError:
            print("Invalid choice(s). Use numbers only.")
            continue
        # keep unique in original order
        seen = []
        for n in nums:
            if n not in seen:
                seen.append(n)
        if any(n < 1 or n > len(ATTACKS) for n in seen):
            print("Invalid choice(s). Try again.")
            continue
        if not (1 <= len(seen) <= 3):
            print("Pick between 1 and 3 unique attacks.")
            continue
        # convert to zero-based enum values
        values = [n - 1 for n in seen]
        return values

def safe_remove_dir(path: Path):
    import shutil
    if path.exists():
        if not path.is_dir():
            path.unlink()
            return
        ans = input(f"Directory '{path}' already exists. Overwrite existing loaf folder? (y/N): ").strip().lower()
        if ans.startswith('y'):
            shutil.rmtree(path)
        else:
            print("Aborting.")
            sys.exit(1)

def write_loaf_json(loaf_dir: Path, flour, salt, sugar, action_space):
    obj = {
        "flour": flour,
        "salt": salt,
        "sugar": sugar,
        "action_space": action_space
    }
    p = loaf_dir / "loaf.json"
    with p.open("w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2)
    print(f"Created {p}")

def write_main_py(loaf_dir: Path, name: str):
    # Use Path(__file__).resolve().parent to locate loaf.json relative to module
    content = f"""from breadbrawl import Loaf
import json
from pathlib import Path
import random

# Auto-generated by setup_loaf.py
NAME = "{name}"

def _load_loaf():
    p = Path(__file__).resolve().parent / "loaf.json"
    with p.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return Loaf.deserialize(data)

your_loaf = _load_loaf()

# Lazy model loading: if model.pt exists and torch is available, a model will be used.
_model = None
try:
    import torch
    from dql_agent import DQNetwork
    model_path = current_dir = Path(__file__).parent.resolve() / "model.pt"
    if model_path.exists():
        _model = DQNetwork(your_loaf, 10, len(your_loaf.action_space))
        _model.load_state_dict(torch.load(model_path))
        _model.eval()
except Exception:
    _model = None

def loaf():
    return your_loaf

def agent(obs):
    # obs is the observation vector; fallback to random if no model or error
    if _model is None:
        return your_loaf.random_attack()
    try:
        return _model.select_action(obs)
    except Exception:
        return your_loaf.random_attack()
"""
    p = loaf_dir / "main.py"
    with p.open("w", encoding="utf-8") as f:
        f.write(content)
    print(f"Created {p}")

def make_training_script(repo_root: Path, loaf_name: str, flour: int, salt: int, sugar: int, action_space):
    src = repo_root / "dql_agent.py"
    if not src.exists():
        print("Warning: dql_agent.py not found at repo root. Training script will not be created.")
        return
    text = src.read_text(encoding="utf-8")

    # Replace the first 'name = "..."' occurrence
    name_re = re.compile(r'(?m)^\s*name\s*=\s*[\'"].*[\'"].*$', re.MULTILINE)
    if name_re.search(text):
        text = name_re.sub(f'name = "{loaf_name}"', text, count=1)
    else:
        # fallback: insert near top
        text = f'name = "{loaf_name}"\n' + text

    # Build attacks list like: Attack.CRUST_CRUSHER, Attack.OVEN_SPRING
    enum_items = ", ".join(f"Attack.{ATTACKS[v]}" for v in action_space)
    loaf_ctor = f'your_loaf = Loaf(flour={flour}, salt={salt}, sugar={sugar}, attacks=[{enum_items}])'

    # Replace the first occurrence of a line that creates a random loaf
    rand_re = re.compile(r'(?m)^(\s*)your_loaf\s*=\s*Loaf\.random_loaf\(\)\s*$', re.MULTILINE)
    m = rand_re.search(text)
    if m:
        indent = m.group(1) or ""
        repl = indent + loaf_ctor
        text = rand_re.sub(repl, text, count=1)
    else:
        # If not found, try to find a reasonable insertion point under if __name__ == "__main__"
        main_re = re.compile(r'(?m)^if\s+__name__\s*==\s*[\'"]__main__[\'"]\s*:\s*$', re.MULTILINE)
        m2 = main_re.search(text)
        if m2:
            # find end of line and insert next line with proper indentation
            insert_pos = m2.end()
            text = text[:insert_pos] + "\n    " + loaf_ctor + text[insert_pos:]
        else:
            # fallback: append at end
            text += "\n" + loaf_ctor + "\n"

    dest = repo_root / f"dql_agent_{loaf_name}.py"
    dest.write_text(text, encoding="utf-8")
    try:
        # make executable on POSIX
        st = dest.stat()
        dest.chmod(st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except Exception:
        pass
    print(f"Created training script: {dest}")
    print(f"Train using: python \"{dest}\"")

def main():
    repo_root = Path.cwd()
    name = prompt_loaf_name()
    flour, salt, sugar = prompt_stats()
    action_space = prompt_attacks()

    loaf_dir = repo_root / name
    safe_remove_dir(loaf_dir)
    loaf_dir.mkdir(parents=True, exist_ok=True)

    write_loaf_json(loaf_dir, flour, salt, sugar, action_space)
    write_main_py(loaf_dir, name)
    make_training_script(repo_root, name, flour, salt, sugar, action_space)

    print("\nSetup complete!\n")
    print(f"Loaf folder: {loaf_dir}")
    print(f" - loaf.json created at {loaf_dir / 'loaf.json'}")
    print(f" - Streamlit module created at {loaf_dir / 'main.py'}")
    print("\nNext steps:\n")
    print("\n1) To train a model for your loaf :")
    print(f"   python \"dql_agent_{name}.py\"")
    print("\n2) To run the arena UI using your loaf as player 1:")
    print(f"   streamlit run agent_arena.py \"{name}/main.py\"")
    print("   Or run the manual-play UI:")
    print("   streamlit run test_interface.py")
    print("\nNotes:")
    print(" - The created module uses a saved model if <NAME>/model.pt exists; otherwise the agent defaults to random actions so you can demo immediately.")
    print(" - If you prefer not to train, run the UI and the loaf will be used with a random policy.")

if __name__ == "__main__":
    main()